const TAMANHO_LINHA_DIGITAVEL = {
    TITULO: 47,
    CONVENIO: 48
}

const MODULOS = {
    MODULO_10: 10,
    MODULO_11: 11
}

const DATA_BASE_FATOR_VENCIMENTO = "1997-10-07"

module.exports = {
    TAMANHO_LINHA_DIGITAVEL,
    MODULOS,
    DATA_BASE_FATOR_VENCIMENTO
}